<a href="https://colab.research.google.com/github/TailUFPB/fundos-imobiliarios/blob/main/EDA_Modelo_FIIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Imports
import pandas as pd
import numpy as np
from babel import numbers

In [ ]:
#Recebendo o CSV dos fundos

url = 'https://raw.githubusercontent.com/humbertonc/CSV_fundos_imobiliarios/main/fundos%20imobiliarios.csv'
df_fiis = pd.read_csv(url)
df_fiis.drop('Unnamed: 0', axis='columns', inplace=True)

# Pré-processamento dos dados

In [ ]:
df_fiis

    Códigodo fundo                Setor  ... VacânciaFinanceira  QuantidadeAtivos
0           ABCP11            Shoppings  ...                NaN                 1
1           AFCR11              Híbrido  ...                NaN                 0
2           AFOF11  Títulos e Val. Mob.  ...                NaN                 0
3           AIEC11   Lajes Corporativas  ...                NaN                 2
4           ALMI11   Lajes Corporativas  ...                NaN                 1
..             ...                  ...  ...                ...               ...
229         XPLG11            Logística  ...              3,20%                13
230         XPML11            Shoppings  ...                NaN                13
231         XPPR11               Outros  ...                NaN                 4
232         XPSF11               Outros  ...                NaN                 0
233         XTED11   Lajes Corporativas  ...            100,00%                 1

[234 rows x 26 columns]

In [ ]:
# Transformando strings em valores númericos
for column in df_fiis.columns:
  new_column = []
  for i in range(len(df_fiis)):
    if df_fiis[column].iloc[i] != np.NaN:
      if type(df_fiis[column].iloc[i]) == str and df_fiis[column].iloc[i][-1] == "%":
        new_column.append(float(".".join(df_fiis[column].iloc[i].split(","))[0:-1]))
      elif type(df_fiis[column].iloc[i]) == str and df_fiis[column].iloc[i][0:2] == "R$":
        new_column.append(float(df_fiis[column].iloc[i].strip('R$ ').replace('.','').replace(',','.')))
      else:
        new_column.append(df_fiis[column].iloc[i])
    else:
      new_column.append(np.NaN)

  df_fiis[column] = pd.DataFrame(new_column)

In [ ]:
df_fiis

    Códigodo fundo                Setor  ...  VacânciaFinanceira  QuantidadeAtivos
0           ABCP11            Shoppings  ...                 NaN                 1
1           AFCR11              Híbrido  ...                 NaN                 0
2           AFOF11  Títulos e Val. Mob.  ...                 NaN                 0
3           AIEC11   Lajes Corporativas  ...                 NaN                 2
4           ALMI11   Lajes Corporativas  ...                 NaN                 1
..             ...                  ...  ...                 ...               ...
229         XPLG11            Logística  ...                 3.2                13
230         XPML11            Shoppings  ...                 NaN                13
231         XPPR11               Outros  ...                 NaN                 4
232         XPSF11               Outros  ...                 NaN                 0
233         XTED11   Lajes Corporativas  ...               100.0                 1

[234 rows x 26 columns]